#!/bin/bash

sudo route add -net 0.0.0.0 netmask 0.0.0.0 gw 192.168.99.112
sudo route del -net 0.0.0.0 netmask 0.0.0.0 gw 192.168.99.1
sudo cp /etc/resolv.conf.l /etc/resolvconf/run/resolv.conf
echo 'open proxy....'
