#!/bin/bash

if [ "$1" == "open" ]; then 
	sudo route add -net 0.0.0.0 netmask 0.0.0.0 gw 192.168.0.104
	sudo route del -net 0.0.0.0 netmask 0.0.0.0 gw 192.168.0.1
	echo 'open proxy....'
fi
if [ "$1" == "close" ]; then 
	sudo route del -net 0.0.0.0 netmask 0.0.0.0 gw 192.168.0.104
	sudo route add -net 0.0.0.0 netmask 0.0.0.0 gw 192.168.0.1
	echo 'close proxy...'
fi

