#!/bin/bash

sudo route del -net 0.0.0.0 netmask 0.0.0.0 gw 192.168.99.112
sudo route add -net 0.0.0.0 netmask 0.0.0.0 gw 192.168.99.1
sudo cp /etc/dns10.248.248.26.conf /etc/resolvconf/run/resolv.conf
echo 'close proxy....'
