#!/bin/bash
sudo route del -net 0.0.0.0 netmask 0.0.0.0 gw 192.168.0.7
sudo route add -net 0.0.0.0 netmask 0.0.0.0 gw 192.168.0.1
sudo cp /etc/192.168.0.1.conf /etc/resolvconf/run/resolv.conf
echo 'close proxy...'


