#!/bin/bash

sudo route add -net 0.0.0.0 netmask 0.0.0.0 gw 192.168.99.109
sudo route del -net 0.0.0.0 netmask 0.0.0.0 gw 192.168.99.1
sudo cp /etc/dns8.8.8.8.conf /etc/resolvconf/run/resolv.conf
echo 'open proxy....'
